### ISSUE TITLE
Setup Eventbrite

### ISSUE THREAD

**Issue by rgbkrk** [jupytercon/sprints#1]
We should set up an eventbrite to get us a semi-accurate headcount for food and drink.

**Comment by Carreau** [comment]
Just to make sure: 

Is the event open to people that have *not registered for the main conference* ?

**Comment by rgbkrk** [comment]
> Is the event open to people that have not registered for the main conference ?

Yes

**Comment by Carreau** [comment]
https://www.eventbrite.com/e/jupytercon-2016-sprints-tickets-36115337948

**Comment by rgbkrk** [comment]
Well done, thanks. Added you to the jupytercon org too @Carreau

**Comment by Carreau** [comment]
Thanks !

**Comment by parente** [comment]
Small "code" review: the URL and title say "JupyterCon 2016 - Sprints". Should be 2017, right?

**Comment by jasongrout** [comment]
Thanks @Carreau!

**Comment by jasongrout** [comment]
Also, it says "on Saturday on Saturday".

Can more than one person edit the eventbrite listing?
